name: CrashBanUsers
author: "HBIDamian"
version: 1.0.0
api: 4.0.0
main: HBIDamian\CrashBanUsers\Main
load: STARTUP
description: "Upon onPlayerLogin, crash banned user's clients will be crashed."

commands:
  crashban:
    description: Bans the player
    usage: "/crashban <player>"
    permission: crashbanusers.command.ban
    aliases:
      - cban
  crashunban:
    description: Unbans the player
    usage: "/crashunban <player>"
    permission: crashbanusers.command.unban
    aliases:
      - crashpardon
      - cpardon


permissions:
  crashbanusers.command.ban:
    description: Allows sender to crash ban players. 
    default: op
  crashbanusers.command.unban:
    description: Allows the sender to pardon crash ban players
    default: op
